---
- hosts: all
  become: yes
  become_user: root
  tasks: 
   - name: Ensure Nginx is at the latest version
     apt:
      update:_cache: true
      name: nginx 
      state: latest
   - name: Make sure Nginx is running
     systemd:
      state: started
      name: nginx