---
apiVersion: v1
kind: Pod
metadata: 
  name: mysql-pod
  labels: 
    environment: "qa"
    app: mysql
spec:
  containers:
    - name: mysql
      image: mysql:latest
      env:
        - name: MYSQL_POD
          value: "mysql"
      ports: 
        - containerPort: 3306
          protocol: TCP    
